//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keylol.ImageGarage.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedState", Namespace="http://schemas.datacontract.org/2004/07/Keylol.Models")]
    public enum ArchivedState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operator = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreferredNameType", Namespace="http://schemas.datacontract.org/2004/07/Keylol.Models")]
    public enum PreferredNameType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chinese = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalPointType", Namespace="http://schemas.datacontract.org/2004/07/Keylol.Models")]
    public enum NormalPointType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Game = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Genre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manufacturer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Platform = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hardware = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleType", Namespace="http://schemas.datacontract.org/2004/07/Keylol.Models")]
    public enum ArticleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        简评 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        评 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        研 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        谈 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        讯 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        档 = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IImageGarageCoordinator", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IImageGarageCoordinator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageGarageCoordinator/Ping", ReplyAction="http://tempuri.org/IImageGarageCoordinator/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageGarageCoordinator/FindArticle", ReplyAction="http://tempuri.org/IImageGarageCoordinator/FindArticleResponse")]
        Keylol.Models.DTO.ArticleDto FindArticle(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageGarageCoordinator/UpdateArticle", ReplyAction="http://tempuri.org/IImageGarageCoordinator/UpdateArticleResponse")]
        void UpdateArticle(string id, string content, string thumbnailImage, byte[] rowVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageGarageCoordinatorChannel : Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageGarageCoordinatorClient : System.ServiceModel.ClientBase<Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator>, Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator {
        
        public ImageGarageCoordinatorClient() {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageGarageCoordinatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public Keylol.Models.DTO.ArticleDto FindArticle(string id) {
            return base.Channel.FindArticle(id);
        }
        
        public void UpdateArticle(string id, string content, string thumbnailImage, byte[] rowVersion) {
            base.Channel.UpdateArticle(id, content, thumbnailImage, rowVersion);
        }
    }
}
