//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keylol.ImageGarage.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IImageGarageCoordinator", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IImageGarageCoordinator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageGarageCoordinator/FindArticle", ReplyAction="http://tempuri.org/IImageGarageCoordinator/FindArticleResponse")]
        Keylol.Models.DTO.ArticleDto FindArticle(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageGarageCoordinator/UpdateArticle", ReplyAction="http://tempuri.org/IImageGarageCoordinator/UpdateArticleResponse")]
        void UpdateArticle(string id, string content, string thumbnailImage, byte[] rowVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageGarageCoordinatorChannel : Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageGarageCoordinatorClient : System.ServiceModel.ClientBase<Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator>, Keylol.ImageGarage.ServiceReference.IImageGarageCoordinator {
        
        public ImageGarageCoordinatorClient() {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageGarageCoordinatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageGarageCoordinatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Keylol.Models.DTO.ArticleDto FindArticle(string id) {
            return base.Channel.FindArticle(id);
        }
        
        public void UpdateArticle(string id, string content, string thumbnailImage, byte[] rowVersion) {
            base.Channel.UpdateArticle(id, content, thumbnailImage, rowVersion);
        }
    }
}
